library(readr)
library(class)
library(gmodels)
library(dplyr)
bcd <- read.csv("D:\\College\\Eswar\\21bq1a4209\\3-1\\ML_lab\\Exp4\\WDBC-data.csv")
str(bcd)
bcd <- select(bcd,-id,-X)
table(bcd$diagnosis)
round(prop.table(table(bcd$diagnosis)) * 100, digits = 1)
sum(is.na(bcd))
head(bcd)
cor(select(bcd,-diagnosis))
summary(bcd)
